SilverStripe\ORM\DatabaseAdmin:
  database: 'silverstripe'
  schema:
    Produk:
      fields:
        Nama: 'Varchar(255)'
        Deskripsi: 'Text'
        Harga: 'Currency'

    Book:
       fields:
          Title: 'Varchar (255)'
          Author: 'Varchar(255)'
          Price: 'Varchar(255)'