---
Name: approutes
After: framework/_config/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    # tulis nama Url yang mau di akses misal http://localhost/Silverstripe-2/teams
    # ini akan menjalankan Controller dari TeamController
    # jika kita akses http://localhost/Silverstripe-2/teams/coba maka fungsi coba() pada controller TeamController akan dijalankan
    'teams//$Action/$ID/$Name': 'TeamController'
    # tulis nama Url yang mau di akses misal http://localhost/Silverstripe-2/tes
    # ini akan menjalankan Controller dari TesController
    # jika kita akses http://localhost/Silverstripe-2/tes/coba maka fungsi coba() pada controller TesController akan dijalankan
    'tes' : 'TesController'
    # 'api' : 'ApiController'
    'api//$Action/$ID/$Name': 'BooksApiController'
    'api2': 'TesApiController'
    'book_crud//$Action/$ID/$OtherID': 'BukuController'
    